### ISSUE TITLE
A couple of issues...

### ISSUE THREAD

**Issue by samcov** [AlenToma/EntityWorker.Core#1]
1. Two projects are unavailable because the don't exist, FastDeepCloner & Generic.LighDataTable, neither of which appear to be needed

2.  Nuget restore fails every time

**Comment by AlenToma** [comment]
Yes i know. for working with the library download the nuget version. for development you you dont need  Generic.LighDataTable amd fastdeepcloner is library in the nuger. you can also download :)

**Comment by samcov** [comment]
That's fine, I can use the nuget version, but do you plan to fix this in the future?

**Comment by AlenToma** [comment]
Yes. 
This project is under development and i'm working parallel with other project.
So when i have spare time will fix it,
Thx for mentioning the issues and please feel free to report any other.

**Comment by samcov** [comment]
No problem, I understand working in parallel, thanks for taking the time to respond!
