### ISSUE TITLE
Many to Many Relationships

### ISSUE THREAD

**Issue by MajorMajor0** [AlenToma/EntityWorker.Core#5]
It's not clear to me how to handle many-to-many relationships in the module builder. I have a number of junction tables in my database. The EF6 database-first behavior would be to generate virtual lists of child elements automatically and hide the junction tables. How is this done in entityworker?

**Comment by AlenToma** [comment]
It all depends on how you design your class, fallow this example https://dzone.com/articles/how-to-handle-a-many-to-many-relationship-in-datab

give me more information on what you want. 
and also have a look at https://github.com/AlenToma/LightData.CMS/blob/master/source/LightData.CMS.Modules/Library/Menus.cs

**Comment by MajorMajor0** [comment]
To be more specific, I have an existing database with a number of junction tables to handle many-to-many relationships, e.g., 

Extisting database tables: 

Class1
Class2
Class1_Class2 (which is a junction table with foreign key columns Class1_ID and Class2_ID)

Desired Entity mapping:

```
public Class1
{
  [PrimaryKey]
  public long ID {get;set;}

  [IndependentData]
  public List<Class2>{ get; set; }
}
public Class2
{
  [PrimaryKey]
  public long ID { get; set; }

  [IndependentData]
  public List<Class1>{ get; set; }
}
```

I may be missing it, but I don't see anything in the EntityWorker examples illustrating a similar relationship.

**Comment by AlenToma** [comment]
yes your are right. you have to create a new class and call it class1Assignment that will look like this fo example 

```csharp
public class class1Assignment {

[PrimaryKey]
 public long ID{get; set;}

[ ForeignKey(typeof(Class1))]
public long Class1Id {get; set;}

[ ForeignKey(typeof(Class2), "clas2Assignment")]
public long class2Id {get; set;} 

 [IndependentData]
public class2 clas2Assignment {get; set;}
}

//now in class 1 you will have a list of class1Assignment 

public Class1
{
  [PrimaryKey]
  public long ID {get;set;}

//  [IndependentData]
  public List<class1Assignment> class1Assignment{ get; set; }
}

```
this is one way the other way is that you add a fogenkey in class2 thet refer to class 1. and no need to change class 1

**Comment by AlenToma** [comment]
I forgat to show how class2 should look like 

```csharp
public class class2
{
[PrimaryKey]
 public long ID{get; set;}

[ ForeignKey(typeof(Class2))]
public long class2ParentID {get; set;}

public list<Class2> class2List{get; set;}
}
```

**Comment by AlenToma** [comment]
Added Many to Many Relationships Sektion to show how this work 
please read https://github.com/AlenToma/EntityWorker.Core/blob/master/Documentation/Many%20to%20Many%20Relationships.md
