### ISSUE TITLE
Error compiling EntityWorker.Core

### ISSUE THREAD

**Issue by ArsenioInojosa** [AlenToma/EntityWorker.Core#6]
Hello, excellent work.

Download the code but the repository.cs file gives an error.

![image](https://user-images.githubusercontent.com/11929923/40994324-f06af704-68c9-11e8-8048-33e97bf17542.png)

**Comment by AlenToma** [comment]
You have to implement the two methods onModuleStart and onmoduleconfigration
 Se https://github.com/AlenToma/EntityWorker.Core/blob/master/Documentation/Repository.md for more information

**Comment by ArsenioInojosa** [comment]
Solved, I implemented the interface.

Replace:
`public Repository (DataBaseTypes dbType = DataBaseTypes.Mssql): base (GetConnectionString (dbType), true, dbType)`

By

`public Repository (DataBaseTypes dbType = DataBaseTypes.Mssql): base (GetConnectionString (dbType), dbType)`

**Comment by AlenToma** [comment]
nice
